feat(web): Add a rate limit to the pages with forms
freelawproject/bigcases2 pull request #185
Opened 2023-04-08 00:08 UTC by ERosendo

This PR fixes #180 using a rate limit decorator.

2023-04-13 16:32 UTC, ERosendo commented
When a request is ratelimited, [django-ratelimit](https://django-ratelimit.readthedocs.io/en/stable/index.html) raises an `exception` that is a subclass of Django’s `PermissionDenied exception`, so the bot serves the text **“403 Forbidden”**, as per [RFC 9110#section-15.5.4](https://datatracker.ietf.org/doc/html/rfc9110.html#section-15.5.4) (the HTTP 1.1 Specification).

We can override the [permission_denied()](https://docs.djangoproject.com/en/4.1/ref/views/#django.views.defaults.permission_denied) view using the [handler403](https://docs.djangoproject.com/en/4.1/ref/urls/#django.conf.urls.handler403) in the root URLconf and catch the ratelimit exception in this custom view to return a different response. The [django-ratelimit](https://django-ratelimit.readthedocs.io/en/stable/index.html) docs show the following example to return a custom response:

```python
def handler403(request, exception=None):
    if isinstance(exception, Ratelimited):
        return HttpResponse('Sorry you are blocked', status=429)
    return HttpResponseForbidden('Forbidden')
```

We can use a custom page that looks like this:

![image](https://user-images.githubusercontent.com/55959657/231823839-c05a54e2-650d-44b6-b6a5-8eda8e386c5e.png)

Let me know what you think.

2023-04-13 16:33 UTC, mlissner commented
Have you checked how CL does this?

2023-04-13 16:48 UTC, ERosendo commented
I've just checked how CL is doing this and It's using [HTTP 429 Too Many Requests](https://tools.ietf.org/html/rfc6585#section-4) status code instead of status code 403. The [django-ratelimit](https://django-ratelimit.readthedocs.io/en/stable/index.html) docs also show an example to use this status code.

2023-04-13 18:19 UTC, ERosendo commented
@mlissner I've tweaked the `settings` module to use the [HTTP 429 Too Many Requests](https://tools.ietf.org/html/rfc6585#section-4) status code and also included a custom template for this   

I've reviewed the issue with the lint and test action. It seems like the cache is not properly loaded. I've applied the fix described in [this comment](https://github.com/actions/setup-python/issues/182#issuecomment-1151091964) and they're working again.

2023-04-18 14:31 UTC, mlissner requested changes
Just a couple little things, thank you!

2023-04-18 14:31 UTC, mlissner commented on bc/core/utils/network.py
> +    rate="1/5m",
This seems pretty aggressive. Like, I could see myself being annoyed with it, if I had a handful of ideas to input. Maybe 5/30m would be better?

2023-04-18 14:31 UTC, mlissner commented on bc/assets/templates/429.html
> +{% block title %}Forbidden (403){% endblock %}
```suggestion
{% block title %}Sorry, Too Many Requests (429){% endblock %}
```

2023-04-18 15:18 UTC, ERosendo commented
@mlissner I've applied the requested changes. Thanks for your comments.

2023-04-18 16:08 UTC, mlissner approved these changes
Cool. Looks great, thank you.

2023-04-18 16:08 UTC, merged