feat(settings): Setup django-ses
freelawproject/bigcases2 pull request #216
Opened 2023-04-27 13:30 UTC by ERosendo

This PR adds [django-ses](https://github.com/django-ses/django-ses) as a dependency and updates the `settings` module. This PR fixes #199.

2023-04-27 22:39 UTC, mlissner requested changes
This looks fine, but for least privilege, we create separate accounts in AWS with email sending permissions. Therefore, we need something like this in aws.py:

```
# SES
AWS_SES_ACCESS_KEY_ID = env("AWS_SES_ACCESS_KEY_ID", default="")
AWS_SES_SECRET_ACCESS_KEY = env("AWS_SES_SECRET_ACCESS_KEY", default="")
```

2023-04-27 23:35 UTC, ERosendo commented
Thanks for your comments. I added the separate access key in the `aws.py` file.

2023-04-28 04:11 UTC, mlissner approved these changes

2023-04-28 04:11 UTC, merged

2023-04-28 04:34 UTC, mlissner commented
I created a new IAM user with SES access and set up and deployed the credentials. I had to also set up a custom `MAIL FROM` domain too, which required more DNS entries. Once that was done, this worked:

```
send_mail(
    subject=f"Testing  email for this moment",
    message="This is a test",
    from_email="noreply@bots.law",
    recipient_list=["mike@free.law"],
)
```

![image](https://user-images.githubusercontent.com/236970/235054716-74220db1-ecc3-4d2f-a95f-0bf7e0c6331b.png)