349 feat monitor low funding bots
freelawproject/bigcases2 pull request #471
Opened 2024-01-18 01:55 UTC by ERosendo

2024-01-19 15:09 UTC, mlissner commented
Hmm, I've only skimmed the code so far, but wouldn't it be easier to get the amount remaining for a group before making a transaction, and then if the cost of the purchase pushes it below the threshold, send the email? 

For example: 
 - threshold is $70
 - amount remaining is $71
 - doc costs $3

When we make that purchase, we'd know to send the email, no, and we wouldn't need redis?

2024-01-19 21:03 UTC, mlissner commented on bc/sponsorship/emails.py
Here's some suggested text:

### Subject

>  [Action Needed]: Please re-up your funding of {bot_name}

If it's easy, the second message could also say:

> [Action Needed, 2nd Notice]: ...

And the third could say:

> [Action Needed, Final Notice]: ...

(If that's not easy, it's not important.)


### Body

The body could say:

> Hello,
> 
> I am writing because the bot you sponsor on bots.law, {bot_name}, is running low on funding.
> 
> It currently has ${amount_remaining}, and you originally funded it with ${original_amount}.
> 
> Thank you for your sponsorship of this bot! We firmly believe that the support you provide contributes important records to our shared cultural history.
> 
> To continue sponsoring this bot, please do two things:
> 
> 1. Make a payment to Free Law Project at: 
> 
>     https://donate.free.law/forms/pay
> 
> 2. Forward your payment receipt to info@free.law so the money can be allocated to your bot (unfortunately this isn't automated yet!).
> 
> Thank you for your continued support of our bots! Bringing this kind of vital information to everybody is an important way to fight misinformation and educate the public.
> 
> Sincerely,
>
> The Free Law Project Team

2024-01-19 21:07 UTC, mlissner commented on bc/sponsorship/utils.py
> +    email: EmailType = emails["confirm_your_new_account"]
This is the wrong key, no?

2024-01-19 21:08 UTC, mlissner requested changes
A couple little things, but I think generally we should take the approach that avoids redis. 

You also asked:

> does this mean the intention is to send a single email as a one-time alert(When the remaining amount falls below the set threshold for the first time)? or should we keep sending updates until the amount rises above the threshold?

Could we do it as a list of thresholds? So, send it when it crosses $75, another at $40, and a last one at <$3 (saying that the sponsorship is spent)? 

Maybe the last one could be cc'ed to info@free.law?

2024-01-22 14:04 UTC, ERosendo commented on bc/sponsorship/utils.py
> +    email: EmailType = emails["confirm_your_new_account"]
You're right. This is the wrong key.

2024-01-22 14:08 UTC, ERosendo commented
> Could we do it as a list of thresholds? 

Yup. The suggested thresholds seem very reasonable. I'll get them implemented right away.

2024-01-23 04:19 UTC, ERosendo commented
@mlissner This PR is ready for another review. 

I've implemented your suggestion about the thresholds and the email's subject. Additionally, I refactored the logic that checks whether we should send an alert or not. Now, it gets the amount remaining for a group before making a transaction.

Let me know what you think.

2024-01-23 22:32 UTC, mlissner requested changes
Two little things, please, then feel free to merge if you're ready. We should also do a little manual work to see if we need to contact anybody. Could you do that too after merging?

2024-01-23 22:32 UTC, mlissner commented on bc/sponsorship/services.py
> +        ):
```suggestion
        ):
            # Purchase will cross low funding threshold. Send an email.
```

2024-01-23 22:32 UTC, mlissner commented on bc/sponsorship/tests/test_services.py
> +        cache.clear()
Do we still need this method?

2024-01-23 22:32 UTC, mlissner approved these changes

2024-01-23 23:04 UTC, ERosendo commented on bc/sponsorship/tests/test_services.py
> +        cache.clear()
You're right. We don't need this.

2024-01-24 01:44 UTC, merged